---
-- USERS
---
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER pagila
IDENTIFIED BY "pagilaPass"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO pagila;

CREATE USER slave
IDENTIFIED BY "SlavePass"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION TO slave;

CREATE USER master 
IDENTIFIED BY "MasterPass"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION TO master;

ALTER SESSION SET CURRENT_SCHEMA = pagila;

---
-- MASTER TABLES
---
CREATE TABLE pagila.country (
    country_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR2(100) NOT NULL,
    last_update TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE pagila.city (
    city_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR2(100) NOT NULL,
    country_id NUMBER NOT NULL,
    last_update TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_city_country FOREIGN KEY (country_id) REFERENCES country(country_id)
);

CREATE TABLE pagila.language (
    language_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CHAR(20) NOT NULL,
    last_update TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE pagila.address (
    address_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR2(100) NOT NULL,
    address2 VARCHAR2(100),
    district VARCHAR2(100) NOT NULL,
    city_id NUMBER NOT NULL,
    postal_code VARCHAR2(100),
    phone VARCHAR2(100) NOT NULL,
    last_update TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_address_city FOREIGN KEY (city_id) REFERENCES city(city_id)
);

CREATE TABLE pagila.actor (
    actor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    last_update TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE pagila.category (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    last_update TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE pagila.store (
    store_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_staff_id NUMBER,
    address_id NUMBER NOT NULL,
    last_update TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_store_address FOREIGN KEY (address_id) REFERENCES address(address_id)
);

CREATE TABLE pagila.staff (
    staff_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    address_id NUMBER NOT NULL,
    email VARCHAR2(100),
    store_id NUMBER NOT NULL,
    active boolean DEFAULT true NOT NULL,
    username VARCHAR2(100) NOT NULL,
    password VARCHAR2(100),
    last_update TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_staff_address FOREIGN KEY (address_id) REFERENCES address(address_id),
    CONSTRAINT fk_staff_store FOREIGN KEY (store_id) REFERENCES store(store_id)
);

CREATE TABLE pagila.film (
    film_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(100) NOT NULL,
    description VARCHAR2(100),
    release_year NUMBER,
    language_id NUMBER NOT NULL,
    original_language_id NUMBER,
    rental_duration smallint DEFAULT 3 NOT NULL,
    rental_rate NUMBER(4,2) DEFAULT 4.99 NOT NULL,
    length smallint,
    replacement_cost NUMBER(5,2) DEFAULT 19.99 NOT NULL,
    rating VARCHAR(6) DEFAULT 'G',
    last_update TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_film_language FOREIGN KEY (language_id) REFERENCES language(language_id),
    CONSTRAINT fk_film_original_language FOREIGN KEY (original_language_id) REFERENCES language(language_id)
);

CREATE TABLE pagila.film_actor (
    actor_id NUMBER NOT NULL,
    film_id NUMBER NOT NULL,
    last_update TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_film_actor_actor FOREIGN KEY (actor_id) REFERENCES actor(actor_id),
    CONSTRAINT fk_film_actor_film FOREIGN KEY (film_id) REFERENCES film(film_id)
);

CREATE TABLE pagila.film_category (
    film_id NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    last_update TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_film_category_film FOREIGN KEY (film_id) REFERENCES film(film_id),
    CONSTRAINT fk_film_category_category FOREIGN KEY (category_id) REFERENCES category(category_id)
);

CREATE TABLE pagila.inventory (
    inventory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id NUMBER NOT NULL,
    store_id NUMBER NOT NULL,
    last_update TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_inventory_film FOREIGN KEY (film_id) REFERENCES film(film_id),
    CONSTRAINT fk_inventory_store FOREIGN KEY (store_id) REFERENCES store(store_id)
);

---
-- SLAVE TABLES
---
CREATE TABLE pagila.customer (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id NUMBER NOT NULL,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    address_id NUMBER NOT NULL,
    activebool boolean DEFAULT true NOT NULL,
    create_date date DEFAULT CURRENT_DATE NOT NULL,
    last_update TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP,
    active NUMBER,
    CONSTRAINT fk_customer_store FOREIGN KEY (store_id) REFERENCES store(store_id),
    CONSTRAINT fk_customer_address FOREIGN KEY (address_id) REFERENCES address(address_id)
);

CREATE TABLE pagila.CUSTOMER_LOG (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation VARCHAR2(10) NOT NULL,
    old_value CLOB,
    new_value CLOB,
    edition_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TRIGGER trg_audit_customer
BEFORE INSERT OR UPDATE OR DELETE ON pagila.customer
FOR EACH ROW
DECLARE
    v_old CLOB;
    v_new CLOB;
    v_operation VARCHAR2(10);
BEGIN
    IF DELETING THEN
        v_operation := 'DELETE';
        v_new := NULL;
        v_old := JSON_OBJECT(
            'CUSTOMER_ID' VALUE :OLD.customer_id,
            'STORE_ID' VALUE :OLD.store_id,
            'FIRST_NAME' VALUE :OLD.first_name,
            'LAST_NAME' VALUE :OLD.last_name,
            'EMAIL' VALUE :OLD.email,
            'ADDRESS_ID' VALUE :OLD.address_id,
            'ACTIVEBOOL' VALUE :OLD.activebool,
            'CREATE_DATE' VALUE :OLD.create_date,
            'LAST_UPDATE' VALUE :OLD.last_update,
            'ACTIVE' VALUE :OLD.active
        );
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_new := JSON_OBJECT(
            'CUSTOMER_ID' VALUE :NEW.customer_id,
            'STORE_ID' VALUE :NEW.store_id,
            'FIRST_NAME' VALUE :NEW.first_name,
            'LAST_NAME' VALUE :NEW.last_name,
            'EMAIL' VALUE :NEW.email,
            'ADDRESS_ID' VALUE :NEW.address_id,
            'ACTIVEBOOL' VALUE :NEW.activebool,
            'CREATE_DATE' VALUE :NEW.create_date,
            'LAST_UPDATE' VALUE :NEW.last_update,
            'ACTIVE' VALUE :NEW.active
        );
        v_old := JSON_OBJECT(
            'CUSTOMER_ID' VALUE :OLD.customer_id,
            'STORE_ID' VALUE :OLD.store_id,
            'FIRST_NAME' VALUE :OLD.first_name,
            'LAST_NAME' VALUE :OLD.last_name,
            'EMAIL' VALUE :OLD.email,
            'ADDRESS_ID' VALUE :OLD.address_id,
            'ACTIVEBOOL' VALUE :OLD.activebool,
            'CREATE_DATE' VALUE :OLD.create_date,
            'LAST_UPDATE' VALUE :OLD.last_update,
            'ACTIVE' VALUE :OLD.active
        );
    ELSE
        v_operation := 'INSERT';
        v_new := JSON_OBJECT(
            'CUSTOMER_ID' VALUE :NEW.customer_id,
            'STORE_ID' VALUE :NEW.store_id,
            'FIRST_NAME' VALUE :NEW.first_name,
            'LAST_NAME' VALUE :NEW.last_name,
            'EMAIL' VALUE :NEW.email,
            'ADDRESS_ID' VALUE :NEW.address_id,
            'ACTIVEBOOL' VALUE :NEW.activebool,
            'CREATE_DATE' VALUE :NEW.create_date,
            'LAST_UPDATE' VALUE :NEW.last_update,
            'ACTIVE' VALUE :NEW.active
        );
        v_old := NULL;
    END IF;

    INSERT INTO CUSTOMER_LOG(operation, old_value, new_value)
    VALUES (v_operation, v_old, v_new);
END;
/

CREATE TABLE pagila.rental (
    rental_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_date TIMESTAMP with time zone NOT NULL,
    inventory_id NUMBER NOT NULL,
    customer_id NUMBER NOT NULL,
    return_date TIMESTAMP with time zone,
    staff_id NUMBER NOT NULL,
    last_update TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_rental_inventory FOREIGN KEY (inventory_id) REFERENCES inventory(inventory_id),
    CONSTRAINT fk_rental_customer FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
    CONSTRAINT fk_rental_staff FOREIGN KEY (staff_id) REFERENCES staff(staff_id)
);

CREATE TABLE pagila.RENTAL_LOG (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation VARCHAR2(10) NOT NULL,
    old_value CLOB,
    new_value CLOB,
    edition_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TRIGGER trg_audit_rental
BEFORE INSERT OR UPDATE OR DELETE ON pagila.rental
FOR EACH ROW
DECLARE
    v_old CLOB;
    v_new CLOB;
    v_operation VARCHAR2(10);
BEGIN
    IF DELETING THEN
        v_operation := 'DELETE';
        v_new := NULL;
        v_old := JSON_OBJECT(
            'RENTAL_ID' VALUE :OLD.rental_id,
            'RENTAL_DATE' VALUE :OLD.rental_date,
            'INVENTORY_ID' VALUE :OLD.inventory_id,
            'CUSTOMER_ID' VALUE :OLD.customer_id,
            'RETURN_DATE' VALUE :OLD.return_date,
            'STAFF_ID' VALUE :OLD.staff_id,
            'LAST_UPDATE' VALUE :OLD.last_update
        );
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_new := JSON_OBJECT(
            'RENTAL_ID' VALUE :NEW.rental_id,
            'RENTAL_DATE' VALUE :NEW.rental_date,
            'INVENTORY_ID' VALUE :NEW.inventory_id,
            'CUSTOMER_ID' VALUE :NEW.customer_id,
            'RETURN_DATE' VALUE :NEW.return_date,
            'STAFF_ID' VALUE :NEW.staff_id,
            'LAST_UPDATE' VALUE :NEW.last_update
        );
        v_old := JSON_OBJECT(
            'RENTAL_ID' VALUE :OLD.rental_id,
            'RENTAL_DATE' VALUE :OLD.rental_date,
            'INVENTORY_ID' VALUE :OLD.inventory_id,
            'CUSTOMER_ID' VALUE :OLD.customer_id,
            'RETURN_DATE' VALUE :OLD.return_date,
            'STAFF_ID' VALUE :OLD.staff_id,
            'LAST_UPDATE' VALUE :OLD.last_update
        );
    ELSE
        v_operation := 'INSERT';
        v_new := JSON_OBJECT(
            'RENTAL_ID' VALUE :NEW.rental_id,
            'RENTAL_DATE' VALUE :NEW.rental_date,
            'INVENTORY_ID' VALUE :NEW.inventory_id,
            'CUSTOMER_ID' VALUE :NEW.customer_id,
            'RETURN_DATE' VALUE :NEW.return_date,
            'STAFF_ID' VALUE :NEW.staff_id,
            'LAST_UPDATE' VALUE :NEW.last_update
        );
        v_old := NULL;
    END IF;

    INSERT INTO RENTAL_LOG(operation, old_value, new_value)
    VALUES (v_operation, v_old, v_new);
END;
/

CREATE TABLE pagila.payment (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    staff_id NUMBER NOT NULL,
    rental_id NUMBER NOT NULL,
    amount NUMBER(5,2) NOT NULL,
    payment_date TIMESTAMP with time zone NOT NULL,
    last_update TIMESTAMP with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_payment_customer FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
    CONSTRAINT fk_payment_staff FOREIGN KEY (staff_id) REFERENCES staff(staff_id),
    CONSTRAINT fk_payment_rental FOREIGN KEY (rental_id) REFERENCES rental(rental_id)
);

CREATE TABLE pagila.PAYMENT_LOG (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation VARCHAR2(10) NOT NULL,
    old_value CLOB,
    new_value CLOB,
    edition_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TRIGGER trg_audit_payment
BEFORE INSERT OR UPDATE OR DELETE ON pagila.payment
FOR EACH ROW
DECLARE
    v_old CLOB;
    v_new CLOB;
    v_operation VARCHAR2(10);
BEGIN
    IF DELETING THEN
        v_operation := 'DELETE';
        v_new := NULL;
        v_old := JSON_OBJECT(
            'PAYMENT_ID' VALUE :OLD.payment_id,
            'CUSTOMER_ID' VALUE :OLD.customer_id,
            'STAFF_ID' VALUE :OLD.staff_id,
            'RENTAL_ID' VALUE :OLD.rental_id,
            'AMOUNT' VALUE :OLD.amount,
            'PAYMENT_DATE' VALUE :OLD.payment_date
        );
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        v_new := JSON_OBJECT(
            'PAYMENT_ID' VALUE :NEW.payment_id,
            'CUSTOMER_ID' VALUE :NEW.customer_id,
            'STAFF_ID' VALUE :NEW.staff_id,
            'RENTAL_ID' VALUE :NEW.rental_id,
            'AMOUNT' VALUE :NEW.amount,
            'PAYMENT_DATE' VALUE :NEW.payment_date
        );
        v_old := JSON_OBJECT(
            'PAYMENT_ID' VALUE :OLD.payment_id,
            'CUSTOMER_ID' VALUE :OLD.customer_id,
            'STAFF_ID' VALUE :OLD.staff_id,
            'RENTAL_ID' VALUE :OLD.rental_id,
            'AMOUNT' VALUE :OLD.amount,
            'PAYMENT_DATE' VALUE :OLD.payment_date
        );
    ELSE
        v_operation := 'INSERT';
        v_new := JSON_OBJECT(
            'PAYMENT_ID' VALUE :NEW.payment_id,
            'CUSTOMER_ID' VALUE :NEW.customer_id,
            'STAFF_ID' VALUE :NEW.staff_id,
            'RENTAL_ID' VALUE :NEW.rental_id,
            'AMOUNT' VALUE :NEW.amount,
            'PAYMENT_DATE' VALUE :NEW.payment_date
        );
        v_old := NULL;
    END IF;

    INSERT INTO PAYMENT_LOG(operation, old_value, new_value)
    VALUES (v_operation, v_old, v_new);
END;
/

COMMIT;
---
-- PERMISSIONS
---
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.actor TO master;
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.category TO master;
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.film TO master;
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.film_actor TO master;
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.film_category TO master;
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.address TO master;
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.city TO master;
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.country TO master;
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.inventory TO master;
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.language TO master;
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.staff TO master;
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.store TO master;

GRANT SELECT ON pagila.actor TO slave;
GRANT SELECT ON pagila.category TO slave;
GRANT SELECT ON pagila.film TO slave;
GRANT SELECT ON pagila.film_actor TO slave;
GRANT SELECT ON pagila.film_category TO slave;
GRANT SELECT ON pagila.address TO slave;
GRANT SELECT ON pagila.city TO slave;
GRANT SELECT ON pagila.country TO slave;
GRANT SELECT ON pagila.inventory TO slave;
GRANT SELECT ON pagila.language TO slave;
GRANT SELECT ON pagila.staff TO slave;
GRANT SELECT ON pagila.store TO slave;

GRANT SELECT ON pagila.customer TO master;
GRANT SELECT ON pagila.customer_log TO master;
GRANT SELECT ON pagila.rental TO master;
GRANT SELECT ON pagila.rental_log TO master;
GRANT SELECT ON pagila.payment TO master;
GRANT SELECT ON pagila.payment_log TO master;

GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.customer TO slave;
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.customer_log TO slave;
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.rental TO slave;
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.rental_log TO slave;
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.payment TO slave;
GRANT SELECT, INSERT, UPDATE, DELETE ON pagila.payment_log TO slave;

COMMIT;
